from github import Github
from doc_sync_bot.models import ChangeType

PR_BODY_TEMPLATE = """## Documentation Update: {title}

**Triggered by:** {repo_name}#{pr_number}
**Change type:** {change_type}
**Generated by:** krkn-doc-sync-bot v0.1

### What changed
Automated documentation sync triggered by changes in upstream repository.
This PR updates/creates the corresponding documentation file `{target_file_path}`.

### Review checklist
{checklist}

### Request changes
Leave a comment starting with `@docs-bot` to request refinements.
Example: `@docs-bot please add a note that this only works on AWS`
"""

CHECKLISTS = {
    ChangeType.NEW_SCENARIO: """- [ ] Frontmatter title, weight, and description are accurate
- [ ] Scenario parameters table contains all configuration variables
- [ ] Formatting follows the Hugo/Docsy structure exactly""",
    
    ChangeType.PARAM_UPDATE: """- [ ] Parameter description is accurate
- [ ] Default value matches the upstream code
- [ ] Table position is correct (alphabetical / logical grouping)""",
    
    ChangeType.CONFIG_CHANGE: """- [ ] Config field description is accurate
- [ ] Schema types match the code structure
- [ ] Position in config doc is logical""",
    
    ChangeType.CLI_FLAG: """- [ ] CLI flags and descriptions are correct
- [ ] Parent command and subcommand associations are accurate""",
    
    ChangeType.UNKNOWN: """- [ ] Verify the entire generated document for correctness
- [ ] Ensure formatting conforms to Hugo conventions"""
}

class PRCreator:
    def __init__(self, github_client):
        self.client = github_client

    def get_checklist(self, change_type: ChangeType) -> str:
        """Returns the reviewer checklist markdown based on ChangeType."""
        return CHECKLISTS.get(change_type, CHECKLISTS[ChangeType.UNKNOWN])

    def create_draft_pr(self, 
                        website_repo_name: str, 
                        target_file_path: str, 
                        updated_content: str, 
                        change_type: ChangeType, 
                        original_repo: str, 
                        original_pr_number: int) -> str:
        """
        Creates a new branch on the website repo, updates/creates the file,
        and opens a draft PR.
        """
        if not self.client.g:
            raise ValueError("GitHub Client is not authenticated.")
            
        repo = self.client.g.get_repo(website_repo_name)
        base_branch = repo.get_branch("main")
        
        # Create a unique branch name
        branch_name = f"docs-sync/pr-{original_pr_number}-{original_repo.replace('/', '-')}"
        
        print(f"Creating branch '{branch_name}'...")
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_branch.commit.sha)
        except Exception as e:
            print(f"Branch '{branch_name}' might already exist: {e}")

        # Try to update the file; if it fails (doesn't exist), create it
        commit_msg = f"docs: Auto-sync from {original_repo} PR #{original_pr_number}"
        try:
            file_contents = repo.get_contents(target_file_path, ref=branch_name)
            print(f"Updating existing file '{target_file_path}'...")
            repo.update_file(
                path=target_file_path,
                message=commit_msg,
                content=updated_content,
                sha=file_contents.sha,
                branch=branch_name
            )
        except Exception:
            print(f"Creating new file '{target_file_path}'...")
            repo.create_file(
                path=target_file_path,
                message=commit_msg,
                content=updated_content,
                branch=branch_name
            )

        # Generate PR description body
        title = target_file_path.split("/")[-1].replace(".md", "").replace("-", " ").title()
        checklist = CHECKLISTS.get(change_type, CHECKLISTS[ChangeType.UNKNOWN])
        pr_body = PR_BODY_TEMPLATE.format(
            title=title,
            repo_name=original_repo,
            pr_number=original_pr_number,
            change_type=change_type.value,
            target_file_path=target_file_path,
            checklist=checklist
        )

        print("Opening Draft PR...")
        pr = repo.create_pull(
            title=f"docs: Sync changes from {original_repo} PR #{original_pr_number}",
            body=pr_body,
            head=branch_name,
            base="main",
            draft=True
        )
        
        print(f"Draft PR created: {pr.html_url}")
        return pr.html_url
